bugfix 'win error on git clone' by rename file
win error on git clone because win does not give store file with file name which contains symbol '?'

error:
>git clone https://github.com/dremio/dremio-oss.git dremio
error: invalid path 'dac/backend/src/test/resources/testfiles/file_with_?.json'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.